# Run docker compose up, wait for it to initialize completely, 
# and visit http://localhost:8080 or http://host-ip:8080 (as appropriate).

services:
  router-ip:
    image: router-ip
    build:
      dockerfile: Dockerfile
    ports:
      - 6789:5432
    # restart: always
    # set shared memory limit when using docker compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: bind
       source: /mnt/usb/
       target: /dbdata/
    environment:
      POSTGRES_USER: lyspfan
      POSTGRES_PASSWORD: lyspfan

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080