# Run docker compose up, wait for it to initialize completely, 
# and visit http://localhost:8080 or http://host-ip:8080 (as appropriate).

services:

  router-ip:
    image: router-ip
    container_name: routerips-db
    build:
      dockerfile: Dockerfile
    ports:
      - 6789:5432
    # restart: always
    # set shared memory limit when using docker compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: bind
       source: /mnt/usb/
       target: /dbdata/
    environment:
      POSTGRES_USER: lyspfan
      POSTGRES_PASSWORD: lyspfan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lyspfan --quiet"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lyspfan@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: lyspfan
    ports:
      - 9876:80
    depends_on:
      router-ip:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: routerips-adminer
    # restart: always
    ports:
      - 8080:8080