# Run docker compose up, wait for it to initialize completely, 
# and visit http://localhost:8080 or http://host-ip:8080 (as appropriate).

services:

  postgres:
    image: postgres:17
    container_name: gateway-db
    ports:
      - 6789:5432
    restart: always
    volumes:
     - type: bind
       source: /cdbdata
       target: /cdbdata
     - type: bind
       source: /cdbdata/pgdata
       target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: gatewayadmin
      POSTGRES_PASSWORD: gatewayadmin
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet --dbname=gateway --username=gatewayadmin || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: gateway-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hopkinsnetslab@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gatewayadmin
    ports:
      - 9876:80
    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: gateway-adminer
    restart: always
    ports:
      - 8080:8080