import sys
import os
import bz2
import ipaddress
from datetime import datetime
import logging as log 
import multiprocessing as mp
from tqdm import tqdm
from collections import defaultdict, Counter

NPROC = 30
CHUCK_SIZE = 50000
now = datetime.now().strftime("%Y%m%d-%H%M%S")
outfile_name = "non_slaac_" + now + ".csv"

'''
check if an address is SLAAC-generated by checking if
EUI-64 is present
    @addr: full expanded ipv6 address without colons
'''
def is_slaac(addr):
    return addr[22:26].lower() == "fffe"

'''
return network ID and host ID of an address
    @addr: full expanded ipv6 address without colons
'''
def split_ip(addr):
    return addr[:16], addr[16:]

'''
filter out addresses generated by SLAAC
'''
def write_non_slaac(chunk):
    loc_total = 0
    loc_slaac_total = 0
    loc_host_dict = defaultdict(list)
    loc_host_counter = Counter()
    loc_nslaac_lines = []

    for line in chunk:
        parts = line.split(",")
        if not len(parts) == 7:
            log.warning("Malformed input data line, skipping")
            continue
        # expand address
        src_ip_str = parts[2].strip()
        # TODO: what do we do if the responding router has a v4 address?
        try:
            src_ip_obj = ipaddress.IPv6Address(src_ip_str)
        except:
            log.warning(f"Responding router {src_ip_str} has a v4 address")
            continue
        full_addr = src_ip_obj.exploded.replace(":", "")
        # filter out slaac addresses
        if is_slaac(full_addr):
            loc_slaac_total += 1
        else:
            loc_nslaac_lines.append(line)
            network_id, host_id = split_ip(full_addr)
            loc_host_dict[host_id].append(network_id)
            loc_host_counter[host_id] += 1
        loc_total += 1

    loc_nslaac_total = loc_total - loc_slaac_total
    return loc_nslaac_lines, loc_total, loc_slaac_total, loc_host_dict, loc_host_counter

'''
process all data
main process hands chucks to worker processes
'''
def main():

    # get and validate names of input files
    if len(sys.argv) < 2:
        print("Usage: python3 filter.py <input1.csv.bz2> <input2.csv.bz2> ...")
        sys.exit(1)
    for filepath in sys.argv[1:]:
        if not os.path.exists(filepath):
            log.error(f"{filepath} not found, please double check")
            sys.exit(1)

    grand_total = 0                      # total number of addr
    grand_slaac_total = 0                # total number of slaac addr
    grand_host_dict = defaultdict(list)  # big dictionary for all
    grand_host_counter = Counter()
    pool = mp.Pool(NPROC)                # create workers
    outfile = open(outfile_name, "w")    # create shared output file

    for filepath in sys.argv[1:]:
        if filepath.endswith(".csv"):
            open_func = open
        elif filepath.endswith(".csv.bz2"):
            open_func = bz2.open
        else:
            log.error("Invalid file format. It should only end with csv or bz2")
            sys.exit(1)

        log.info(f"Started processing [{filepath}]")
        curr_chuck = []
        result_objs = []

        infile = open_func(filepath, "rt")
        for line in infile:
            line = line.strip()
            if line.startswith("#"): continue
            if len(curr_chuck) <= CHUCK_SIZE:
                curr_chuck.append(line)
            else:
                result = pool.apply_async(write_non_slaac, (curr_chuck,))
                result_objs.append(result)
                curr_chuck = []
        if curr_chuck:
            result = pool.apply_async(write_non_slaac, (curr_chuck,))
            result_objs.append(result)
            
        for ro in result_objs:
            loc_nslaac_lines, loc_total, loc_slaac_total, loc_host_dict, loc_host_counter = ro.get()
            outfile.write('\n'.join(loc_nslaac_lines)+'\n')
            grand_total += loc_total
            grand_slaac_total += loc_slaac_total
            for host_id, network_ids in loc_host_dict.items():
                grand_host_dict[host_id].extend(network_ids)
            grand_host_counter += loc_host_counter

        infile.close()
        log.info(f"Finished processing [{filepath}]")

    outfile.close()
    pool.close()

    print(f"SUMMARY")
    print("="*20)
    print(f"Total number of address processed: {grand_total}")
    print(f"Total number of SLAAC address: {grand_slaac_total}")
    print(f"Total number of non-SLAAC address: {grand_total - grand_slaac_total}")
    print(f"Top 20 most repeated host addresses")
    print(f"  {'Count':>10}  {'Host ID':>35}")
    print(f"  {'-'*10}  {'-'*35}")
    for host_id, count in grand_host_counter.most_common(20):
        formatted = f"{host_id[0:4]}:{host_id[4:8]}:{host_id[8:12]}:{host_id[12:16]}"
        print(f"  {count:>10,}  {formatted:>35}")
if __name__ == "__main__":
    main()