CREATE EXTENSION plpython3u;

-- return host ID of an address
--   @addr: full expanded ipv6 address without colons
CREATE FUNCTION get_hid(addr text)
  RETURNS text
AS $$
  return addr[64:]
$$ LANGUAGE plpython3u;

-- return network ID of an address
--   @addr: full expanded ipv6 address without colons
CREATE FUNCTION get_nid(addr text)
  RETURNS text
AS $$
  return addr[:64]
$$ LANGUAGE plpython3u;

-- expand an ipv6 address to its full 32-character form
-- with no colons or shorthand notation
--   @addr: compressed ipv6 address (e.g. 2001:db8::1)
CREATE FUNCTION exploded(src_ip_str text)
  RETURNS text
AS $$
  import ipaddress
  src_ip_obj = ipaddress.IPv6Address(src_ip_str)
  full_addr = src_ip_obj.exploded.replace(":", "")
  return full_addr
$$ LANGUAGE plpython3u;

-- 64 binary bits, each can take on the value of 0 or 1
--   @hid: host id of router
-- also i lowkey don't think shannon entropy is a good idea because 
-- it does not account for the location at which things appear
-- but only the probability
CREATE FUNCTION shannon_bin(hid text)
  RETURNS float
AS $$
  from collections import Counter
  from math import log2
  binary = bin(int(hid, 16))[2:].zfill(64)
  c = Counter(binary)
  score = - sum([(val / 64) * log2(val / 64) for key, val in c.items()])
  return score
$$ LANGUAGE plpython3u;

CREATE FUNCTION shannon_hex(hid text)
  RETURNS float
AS $$
  from collections import Counter
  from math import log2
  c = Counter(hid)
  score = - sum([(val / 16) * log2(val / 16) for key, val in c.items()])
  return score
$$ LANGUAGE plpython3u;

-- check if an address is in IPv4
CREATE FUNCTION is_v6(src_ip_str text) 
  RETURNS boolean
AS $$
  import ipaddress
  try:
    obj = ipaddress.IPv6Address(src_ip_str)
    return True
  except:
    return False
$$ LANGUAGE plpython3u;

CREATE FUNCTION exploded(src_ip_str text)
  RETURNS text
AS $$
  import ipaddress
  try: 
    src_ip_obj = ipaddress.IPv6Address(src_ip_str)
    return src_ip_obj.exploded.replace(":", "")

$$ LANGUAGE plpython3u;

-- check if an address is SLAAC-generated by checking if
-- EUI-64 marker (FFFE) is present
--   @addr: full expanded ipv6 address without colons
CREATE FUNCTION is_slaac(addr text)
  RETURNS boolean
AS $$
  return addr[22:26].lower() == "fffe"
$$ LANGUAGE plpython3u;